### ISSUE TITLE
Openstaande verlofaanvragen wijzigen/verwijderen

### ISSUE THREAD

**Issue by LeslytH** [laagligger/operum-issuetracker#6]
Request:
Mogelijkheid om openstaande verlofaanvragen te wijzigen of verwijderen, dit in verband met het voorkomen van foutieve aanvragen binnen operum.

Zo houden de gebruikers van het systeem meer overzicht

**Comment by laagligger** [comment]
Zodra de verlofaanvraag functionaliteit volledig(er) ingebouwd is zullen openstaande verlofaanvragen nog verwijderd worden. Na het bevestigen vanuit Admin/Beheerder kan alleen diegene de aanvraag verwijderen. Dan zal de gebruiker een Admin/Beheerder moeten benaderen om deze aanvraag te verwijderen.

**Comment by laagligger** [comment]
De aangevraagde functie is als volgt ingebouwd;

Zolang de verlofaanvraag open is, en dus niet beoordeeld door een admin/beheerder kan de gebruiker zijn of haar verlofaanvraag nog verwijderen. Zodra de verlofaanvraag beoordeeld is, kan een admin/beheerder alleen de beoordeling nog wijzigen.
