### ISSUE TITLE
Totaal gewerkte uren per dag

### ISSUE THREAD

**Issue by Chimanski** [laagligger/operum-issuetracker#8]
Mogelijkheid om naast de begin, eind en pauze tijd. De totaal gewerkte tijd per dag te kunnen zien.
Voorbeeld:
Begin: 7:30 Eind: 16:30 Pauze: 1,00 totaal gewerkt: 8,00 uur

**Comment by laagligger** [comment]
Deze functie kan toegevoegd worden aan het uren overzicht. Zodra deze functie ingebouwd is en uitvoerig getest is zal dit automatisch in het uren overzicht verschijnen.

**Comment by laagligger** [comment]
De functie is in het overzicht verwerkt in de kolom "Gewerkt".

Deze functie is zeer minimaal getest en zal later verder getest worden.
